server:
  port: ${PORT:${SERVER_PORT:0}}


spring:
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/Micro
    driverClassName: org.postgresql.Driver
    username: postgres
    password: user

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false

eureka:
  client:
    fetch_registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
